#!/bin/bash -e

function die()
{
	echo "Error: $1" >&2
	exit 1
}

function logmsg()
{
	echo "[`date`] $*"
}

[ -z "$LOCAL_DIR" ] && die "No base dir specified"
[ -z "$TARGET" ] && die "No package target specified"
[ -z "$PACKAGE" ] && die "No package name specified"
[ ! -d "$LOCAL_DIR" ] && die "$LOCAL_DIR does not exist"
[ -z "$TARGET" ] && die "Invalid target: $TARGET"

pushd $LOCAL_DIR

mkdir -p deb/usr/share/$PACKAGE

export JAVA_HOME=/usr/lib/jvm/j2sdk1.8-oracle
echo "Building collector"
./gradlew :zipkin-collector-service:installDist --stacktrace
echo "Building query"
./gradlew :zipkin-query-service:installDist --stacktrace
echo "Building web"
./gradlew :zipkin-web:installDist --stacktrace

echo "Copying collector"
cp -r zipkin-collector-service/build/install/* deb/usr/share/$PACKAGE
mkdir -p deb/usr/share/$PACKAGE/zipkin-collector-service/resources
cp zipkin-collector-service/config/collector-cassandra.scala deb/usr/share/$PACKAGE/zipkin-collector-service/resources

echo "Copying query"
cp -r zipkin-query-service/build/install/* deb/usr/share/$PACKAGE
mkdir -p deb/usr/share/$PACKAGE/zipkin-query-service/resources
cp zipkin-query-service/config/query-cassandra.scala deb/usr/share/$PACKAGE/zipkin-query-service/resources

echo "Copying web"
cp -r zipkin-web/build/install/* deb/usr/share/$PACKAGE
mkdir -p deb/usr/share/$PACKAGE/zipkin-web/resources
cp -r zipkin-web/build/resources/main/* deb/usr/share/$PACKAGE/zipkin-web/resources

logmsg "Done"


