#!/bin/bash

CMD="$1"

PAC=fk-zipkin

if [ "$1" == "upgrade" ]; then
	exit 0;
fi

if [ "$1" == "purge" ] ; then
    if [ -d "/var/log/flipkart/$PAC" ]; then
 	    rm -rf "/var/log/flipkart/$PAC"
    fi

    if [ -d "/var/run/$PAC" ]; then
        rm -rf "/var/run/$PAC"
    fi

    if [ -f "/etc/confd/conf.d/collector-cassandra.toml" ]; then
        rm -f "/etc/confd/conf.d/collector-cassandra.toml"
    fi

    if [ -f "/etc/confd/conf.d/query-cassandra.toml" ]; then
        rm -f "/etc/confd/conf.d/query-cassandra.toml"
    fi

    if [ -f "/etc/confd/templates/collector-cassandra.scala.tmpl" ]; then
        rm -f "/etc/confd/templates/collector-cassandra.scala.tmpl"
    fi

    if [ -f "/etc/confd/templates/query-cassandra.scala.tmpl" ]; then
        rm -f "/etc/confd/templates/query-cassandra.scala.tmpl"
    fi

    if [ -d "/usr/share/$PAC" ] ; then
        rm -rf "/usr/share/$PAC"
    fi
fi
exit 0
